#!/usr/bin/env bash
#
# check-b2-config-reads.sh — guardrail against new raw config-table reads
# in B.2-scope modules.
#
# Per docs/follow-ups/b2-survey-and-design.md §0.2 + §0.3:
#   - The committed effective workflow / SLA plan lives on the runtime row
#     (tickets.workflow_id / sla_id, work_orders.workflow_id / sla_id) once
#     B.2.A ships.
#   - Code that READS workflow_definition_id / sla_policy_id /
#     case_sla_policy_id outside the few legitimate sites (resolver, plan-
#     build, reclassify, schema column accesses) is the failure-class that
#     produced the v3-v9 spec leak rounds.
#
# This script is content-keyed (no line numbers) so a refactor that shifts
# lines without changing meaning doesn't false-fail. A refactor that adds
# a new raw read OR changes the content of an existing one will fail and
# require the reviewer to either fix the read or update the allowlist.
#
# Modes:
#   check-b2-config-reads.sh           scan + diff (CI default)
#   check-b2-config-reads.sh --staged  same scan, but skip cleanly if no
#                                      B.2-scope files are staged. Pre-
#                                      commit hook mode.
#   check-b2-config-reads.sh --gen     regenerate the allowlist (use when
#                                      legitimate refactor changed content)

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# In --staged mode skip cleanly if no B.2-scope source files are staged.
# Same shape as check-design.sh.
if [ "${1:-}" = "--staged" ]; then
  STAGED=$(git diff --cached --name-only --diff-filter=AM 2>/dev/null \
    | grep -E "^apps/api/src/modules/(ticket|sla|approval|workflow|portal)/.*\.ts$" \
    | grep -v "\.spec\.ts$" \
    || true)
  ALLOWLIST_STAGED=$(git diff --cached --name-only --diff-filter=AM 2>/dev/null \
    | grep -E "^apps/api/src/modules/\.b2-config-reads-allowlist\.txt$" \
    || true)
  if [ -z "$STAGED" ] && [ -z "$ALLOWLIST_STAGED" ]; then
    echo "B.2 config-reads check skipped — no B.2-scope files staged."
    exit 0
  fi
  shift
fi

ALLOWLIST="apps/api/src/modules/.b2-config-reads-allowlist.txt"
SCOPE="apps/api/src/modules/ticket apps/api/src/modules/sla apps/api/src/modules/approval apps/api/src/modules/workflow apps/api/src/modules/portal"

# Generate the current snapshot.
#
# Pipeline:
#   1. rg --no-line-number → emits `file:content`. Path-sorted by default.
#   2. Strip *.spec.ts files (regression specs may match by design).
#   3. Strip TypeScript field-declaration noise (`sla_policy_id: string;`).
#      Pattern: line ending with the bare property declaration.
#   4. sort -u — deterministic output, dedupes any same-content collisions.
generate_snapshot() {
  # shellcheck disable=SC2086
  rg --type ts --no-line-number \
    "\b(workflow_definition_id|sla_policy_id|case_sla_policy_id)\b" \
    $SCOPE \
    | grep -v "\.spec\.ts:" \
    | grep -vE ":\s*[a-z_]+\??:\s*string" \
    | sort -u
}

if [ "${1:-}" = "--gen" ]; then
  echo "Regenerating $ALLOWLIST from current main..."
  {
    cat <<'EOF'
# B.2 raw config-reads allowlist
# ------------------------------
# Each line is the EXACT ripgrep output (file:content), with line numbers
# stripped and the result sorted+deduped. Generated by
#   scripts/check-b2-config-reads.sh --gen
#
# Why this exists: docs/follow-ups/b2-survey-and-design.md §0.2 + §0.3.
# The B.2 contract says the runtime row carries the effective workflow /
# SLA plan after create/grant/reclassify. Raw reads of
#   workflow_definition_id, sla_policy_id, case_sla_policy_id
# in B.2-scope modules are limited to: resolver/plan-build, reclassify
# resolution, runtime column accesses on sla_timers, workflow node config
# payload, doc comments. Anything else is a failure-class regression.
#
# Lifecycle:
#   - "legit": permanent. Documented as a legitimate read in §0.2.
#   - "to-fix": temporary. Will be eliminated when the named B.2.A RPC
#     ships (§3.5 / §3.10 / §3.11). Tagged inline.
#   - "pending review": new entry that hasn't been triaged. CI fails on
#     any pending-review entry.
#
# This is a SNAPSHOT, not approval-forever. Re-triage on every PR that
# touches a B.2-scope module.
#
# Format: each non-comment line is a content key, sorted.

EOF
    generate_snapshot
  } > "$ALLOWLIST"
  echo "Wrote $(wc -l < "$ALLOWLIST" | tr -d ' ') lines to $ALLOWLIST"
  exit 0
fi

if [ ! -f "$ALLOWLIST" ]; then
  echo "ERROR: $ALLOWLIST does not exist. Run with --gen to bootstrap." >&2
  exit 1
fi

CURRENT=$(mktemp)
ALLOWED=$(mktemp)
trap "rm -f $CURRENT $ALLOWED" EXIT

generate_snapshot > "$CURRENT"
# Strip comments + blank lines from the allowlist for diff.
grep -v "^#" "$ALLOWLIST" | grep -v "^$" | sort -u > "$ALLOWED"

if diff -q "$ALLOWED" "$CURRENT" > /dev/null 2>&1; then
  echo "B.2 config-reads check: OK ($(wc -l < "$CURRENT" | tr -d ' ') entries)"
  exit 0
fi

echo "FAIL: B.2 config reads diverged from allowlist"
echo
echo "  --- expected (allowlist) → +++ actual (current)"
diff -u "$ALLOWED" "$CURRENT" | grep -E "^[+-]" | grep -v "^[+-]\{3\}" | head -40
echo
echo "Either:"
echo "  - Fix the read (preferred — runtime row is source of truth post-create)"
echo "  - Regenerate the allowlist:  bash scripts/check-b2-config-reads.sh --gen"
echo "    Then triage the new entries in $ALLOWLIST"
exit 1
