-- Daglijst Phase A · Sprint 1
-- Schema additions for the paper-vendor "daily list" subsystem.
--
-- Spec: docs/superpowers/specs/2026-04-27-vendor-portal-phase-a-daglijst-design.md §3.
--
-- Why: many EU catering vendors (per `project_vendor_fulfillment_reality.md`)
-- run their kitchen off a printed PDF that lands in their inbox the night
-- before. We assemble + email that PDF on a per-(vendor, building, date)
-- bucket schedule. This migration ships the data plane only — the worker
-- + PDF rendering land in Sprint 2.

-- =====================================================================
-- vendors: fulfillment-mode + daglijst delivery configuration
-- =====================================================================

alter table public.vendors
  add column if not exists fulfillment_mode text not null default 'paper_only',
  add column if not exists daglijst_email text,
  add column if not exists daglijst_cutoff_offset_minutes int not null default 180,
  add column if not exists daglijst_send_clock_time time,
  add column if not exists daglijst_language text not null default 'nl',
  add column if not exists daglijst_inferred_status_grace_minutes int not null default 30;

do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'vendors_fulfillment_mode_chk'
  ) then
    alter table public.vendors
      add constraint vendors_fulfillment_mode_chk
        check (fulfillment_mode in ('portal','paper_only','hybrid'));
  end if;

  if not exists (
    select 1 from pg_constraint
     where conname = 'vendors_daglijst_language_chk'
  ) then
    alter table public.vendors
      add constraint vendors_daglijst_language_chk
        check (daglijst_language in ('nl','fr','en','de'));
  end if;

  -- Either offset OR clock-time mode, not both.
  if not exists (
    select 1 from pg_constraint
     where conname = 'vendors_daglijst_send_mode_chk'
  ) then
    alter table public.vendors
      add constraint vendors_daglijst_send_mode_chk
        check (
          daglijst_send_clock_time is null
          or daglijst_cutoff_offset_minutes = 180   -- default; "ignored when clock_time is set"
        );
  end if;
end
$$;

comment on column public.vendors.fulfillment_mode is
  'How this vendor receives orders: portal (login), paper_only (daglijst PDF email), or hybrid. See vendor-portal-phase-a-daglijst-design.md §2.';
comment on column public.vendors.daglijst_email is
  'Recipient for the daglijst PDF email. Required when fulfillment_mode includes paper_only/hybrid; nullable so vendors can be created portal-first then opt in.';

-- =====================================================================
-- vendor_daily_lists: one row per (vendor, building, service_type, date, version)
-- =====================================================================

create table if not exists public.vendor_daily_lists (
  id                   uuid        primary key default gen_random_uuid(),
  tenant_id            uuid        not null references public.tenants(id) on delete cascade,
  vendor_id            uuid        not null references public.vendors(id) on delete cascade,
  building_id          uuid        references public.spaces(id),       -- nullable when vendor delivers tenant-wide
  service_type         text        not null,
  list_date            date        not null,
  version              int         not null,
  payload              jsonb       not null,                            -- snapshot of orders + items at generation time
  pdf_storage_path     text,                                            -- supabase storage path; null until Sprint 2 renders it
  pdf_url_expires_at   timestamptz,
  generated_at         timestamptz not null default now(),
  generated_by_user_id uuid        references public.users(id),         -- null = auto-generated by scheduler
  sent_at              timestamptz,
  recipient_email      text,
  email_message_id     text,                                            -- provider message id for bounce tracking
  email_status         text,
  email_error          text,
  created_at           timestamptz not null default now(),

  constraint daglijst_email_status_chk check (
    email_status is null or email_status in
      ('queued','sent','delivered','bounced','failed','never_sent')
  ),
  constraint daglijst_version_positive check (version > 0)
);

create unique index if not exists uq_daglijst_version
  on public.vendor_daily_lists (tenant_id, vendor_id, building_id, service_type, list_date, version);

create index if not exists idx_daglijst_pending_send
  on public.vendor_daily_lists (tenant_id, sent_at)
  where sent_at is null;

create index if not exists idx_daglijst_history
  on public.vendor_daily_lists (tenant_id, vendor_id, list_date desc);

alter table public.vendor_daily_lists enable row level security;

drop policy if exists vendor_daily_lists_select on public.vendor_daily_lists;
create policy vendor_daily_lists_select on public.vendor_daily_lists
  for select using (
    tenant_id = public.current_tenant_id()
    and (
      auth.role() = 'service_role'
      or public.user_has_permission(
        (select id from public.users where auth_uid = auth.uid() and tenant_id = public.current_tenant_id() limit 1),
        public.current_tenant_id(),
        'vendors.read'
      )
    )
  );

drop policy if exists vendor_daily_lists_modify on public.vendor_daily_lists;
create policy vendor_daily_lists_modify on public.vendor_daily_lists
  for all using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

comment on table public.vendor_daily_lists is
  'Per-(vendor, building, service_type, date, version) snapshot of orders sent to a paper-mode vendor. See daglijst-design.md §3.';

-- =====================================================================
-- order_line_items: lock + phone-followup tracking
-- =====================================================================

alter table public.order_line_items
  add column if not exists daglijst_locked_at                 timestamptz,
  add column if not exists daglijst_id                        uuid references public.vendor_daily_lists(id),
  add column if not exists requires_phone_followup            boolean not null default false,
  add column if not exists desk_confirmed_phoned_at           timestamptz,
  add column if not exists desk_confirmed_phoned_by_user_id   uuid references public.users(id);

create index if not exists idx_oli_phone_followup
  on public.order_line_items (tenant_id, requires_phone_followup, service_window_start_at)
  where requires_phone_followup = true and desk_confirmed_phoned_at is null;

comment on column public.order_line_items.daglijst_locked_at is
  'When the line was locked into a sent daglijst version. Edits after this time set requires_phone_followup=true so the desk follows up by phone.';

notify pgrst, 'reload schema';
