-- Step 1c.2 of docs/data-model-step1c-plan.md: backfill work_orders_new
-- from tickets where ticket_kind='work_order'.
--
-- Idempotent via legacy_ticket_id UNIQUE — re-running this migration
-- doesn't duplicate rows (ON CONFLICT DO NOTHING).
--
-- Per phase 1c.0 baseline (docs/follow-ups/step1c-baseline.md), 319 rows
-- expected on remote. Production may differ — re-baseline before applying
-- there.

insert into public.work_orders_new (
  id,
  tenant_id,
  ticket_type_id,
  parent_kind,
  parent_case_id,
  booking_bundle_id,
  title,
  description,
  status,
  status_category,
  waiting_reason,
  interaction_mode,
  priority,
  impact,
  urgency,
  requester_person_id,
  requested_for_person_id,
  location_id,
  asset_id,
  assigned_team_id,
  assigned_user_id,
  assigned_vendor_id,
  workflow_id,
  sla_id,
  source_channel,
  tags,
  watchers,
  cost,
  satisfaction_rating,
  satisfaction_comment,
  form_data,
  sla_response_due_at,
  sla_resolution_due_at,
  sla_response_breached_at,
  sla_resolution_breached_at,
  sla_at_risk,
  sla_paused,
  sla_paused_at,
  sla_total_paused_minutes,
  module_number,
  external_system,
  external_id,
  linked_order_line_item_id,
  planned_start_at,
  planned_duration_minutes,
  reclassified_at,
  reclassified_from_id,
  reclassified_reason,
  reclassified_by,
  close_reason,
  closed_by,
  created_at,
  updated_at,
  resolved_at,
  closed_at,
  legacy_ticket_id
)
select
  t.id,
  t.tenant_id,
  t.ticket_type_id,
  case
    when t.booking_bundle_id is not null then 'booking_bundle'
    when t.parent_ticket_id is not null  then 'case'
    else null
  end as parent_kind,
  t.parent_ticket_id as parent_case_id,
  t.booking_bundle_id,
  t.title,
  t.description,
  t.status,
  t.status_category,
  t.waiting_reason,
  t.interaction_mode,
  t.priority,
  t.impact,
  t.urgency,
  t.requester_person_id,
  t.requested_for_person_id,
  t.location_id,
  t.asset_id,
  t.assigned_team_id,
  t.assigned_user_id,
  t.assigned_vendor_id,
  t.workflow_id,
  t.sla_id,
  t.source_channel,
  coalesce(t.tags, '{}'::text[]),
  coalesce(t.watchers, '{}'::uuid[]),
  t.cost,
  t.satisfaction_rating,
  t.satisfaction_comment,
  t.form_data,
  t.sla_response_due_at,
  t.sla_resolution_due_at,
  t.sla_response_breached_at,
  t.sla_resolution_breached_at,
  t.sla_at_risk,
  t.sla_paused,
  t.sla_paused_at,
  t.sla_total_paused_minutes,
  t.module_number,
  t.external_system,
  t.external_id,
  t.linked_order_line_item_id,
  t.planned_start_at,
  t.planned_duration_minutes,
  t.reclassified_at,
  t.reclassified_from_id,
  t.reclassified_reason,
  t.reclassified_by,
  t.close_reason,
  t.closed_by,
  t.created_at,
  t.updated_at,
  t.resolved_at,
  t.closed_at,
  t.id  -- legacy_ticket_id = source ticket id
from public.tickets t
where t.ticket_kind = 'work_order'
on conflict (legacy_ticket_id) do nothing;

notify pgrst, 'reload schema';
