/**
 * Portal submit types. Not exported from @prequest/shared because PortalAvailabilityTrace
 * is portal-local UX diagnostic, not part of any routing contract.
 * See docs/portal-scope-slice.md §2
 */

export interface PortalSubmitDto {
  request_type_id: string;
  location_id?: string | null;   // user-picked; never prefilled from asset
  asset_id?: string | null;
  priority?: 'low' | 'normal' | 'high' | 'urgent';
  title: string;
  description?: string;
  form_data?: Record<string, unknown>;
}

/**
 * All fields always present. Generated by public.portal_availability_trace() SQL function.
 */
export interface PortalAvailabilityTrace {
  authorized: boolean;
  has_any_scope: boolean;
  effective_location_id: string | null;
  matched_root_id: string | null;
  matched_root_source: 'default' | 'grant' | null;
  grant_id: string | null;
  visible: boolean;
  location_required: boolean;
  granularity: string | null;
  granularity_ok: boolean;
  overall_valid: boolean;
  failure_reason: string | null;
}
