/**
 * Portal submit types. Not exported from @prequest/shared because PortalAvailabilityTrace
 * is portal-local UX diagnostic, not part of any routing contract.
 * See docs/portal-scope-slice.md §2
 */

export interface PortalSubmitDto {
  /**
   * Preferred in service-catalog v2. When set, resolves fulfillment via
   * service_items.fulfillment_type_id and runs portal_requestable_trace.
   */
  service_item_id?: string;
  /**
   * Legacy; when set without service_item_id, the backend resolves it via the
   * request_type_service_item_bridge to the paired service item.
   */
  request_type_id?: string;
  location_id?: string | null;   // user-picked; never prefilled from asset
  asset_id?: string | null;
  requested_for_person_id?: string | null;
  priority?: 'low' | 'normal' | 'high' | 'urgent';
  impact?: string;
  urgency?: string;
  title: string;
  description?: string;
  form_data?: Record<string, unknown>;
}

/**
 * All fields always present. Generated by public.portal_availability_trace()
 * or portal_requestable_trace(). Shape below is the shipped (v1) superset.
 */
export interface PortalAvailabilityTrace {
  authorized: boolean;
  has_any_scope: boolean;
  effective_location_id: string | null;
  matched_root_id: string | null;
  matched_root_source: 'default' | 'grant' | null;
  grant_id: string | null;
  visible: boolean;
  location_required: boolean;
  granularity: string | null;
  granularity_ok: boolean;
  overall_valid: boolean;
  failure_reason: string | null;
}

/**
 * Strict superset returned by portal_requestable_trace() — adds service-item
 * and criteria/on-behalf/asset fields. Portal-local; not stored on tickets.
 */
export interface PortalRequestableTrace extends PortalAvailabilityTrace {
  service_item_id: string;
  fulfillment_type_id: string;
  matched_offering_id: string | null;
  matched_form_variant_id: string | null;
  criteria: {
    visible_allow_required: boolean;
    visible_allow_ok: boolean;
    visible_deny_ok: boolean;
    request_allow_required: boolean;
    request_allow_ok: boolean;
    request_deny_ok: boolean;
  };
  on_behalf_ok: boolean;
  asset_type_filter_ok: boolean;
}
